### ISSUE TITLE
 micropython-micropower/upower.py does not support Espruino Pico

### ISSUE THREAD

**Issue by kmartinez** [peterhinch/micropython-micropower#1]
micropython-micropower/upower.py does not work on the Espruino Pico as it does not have Pin X1 defined, so line 183 throws an error. Changing X1 to A0 allows this to work as expected.

**Comment by peterhinch** [comment]
Thanks for the report. Unfortunately this change would fail on the Pyboard which does not have A0 defined. For the moment I'll put a comment in the code. I haven't tested this on targets other than the Pyboard variants so there may well be other issues. I'd welcome any further comments on compatibility.

**Comment by kmartinez** [comment]
good idea - the Pico is probably just one of the many boards with different pin-names. You'll be happy to hear your code helped us get 5uA sleep/wake on the Pico.

**Comment by peterhinch** [comment]
Glad to hear it's working. I did consider using an exception but my Micropower repo aims to suggest techniques to programmers; it isn't a cross-platform solution. I therefore concluded that the KISS principle coupled with comments is the best way to handle cross-platform issues.
